### ISSUE TITLE
Scripts seem to no longer work

### ISSUE THREAD

**Issue by CompSciDude1** [Zerg00s/Live-Captions-Saver#14]
I recently started using this to capture live captions around 5/20.  For some reason, now they don't seem to work.  I copy and paste either the JSON or YAML script into the Developer console, but I no longer see captions being captured.  When I try downloading the JSON or YAML, the file is empty.

I am using the Teams web client and Edge Version 132.0.2957.140.

**Comment by Zerg00s** [comment]
Hi @CompSciDude1, I fixed the issue. The new version 3.6 is expected to be published soon, within a day or so, once it passes the review by the Chrome Store.

I also updated the standalone JSON and YAML scripts. They should work now.

**Comment by zm005** [comment]
still not working for me. if I click on the Save captions button nothing happens. it was working perfectly like 2 weeks ago , I made a lot of txt file from Teams caption but it stopped forking 1-2 weeks ago 

![Image](https://github.com/user-attachments/assets/8dca654c-3e03-4ecf-b272-ae710c6dce10)

**Comment by beniouse** [comment]
Hello, thank you so much for your work ! we have created a new issue as the version is currently having an issue
